### PR TITLE
Remove MinVerTagPrefix

### PR DESCRIPTION
**Pull request by sungam3r**

### CODE REVIEW

**Comment by ArieGato** [comment]
Are you sure that the version will still be 7.0.0-pre…?

**Comment by ArieGato** [comment]
I prefer that the tags begin with a ‘v’. The Serilog repository also prefixes tags with a v

**Comment by sungam3r** [comment]
`MinVerTagPrefix` is useless if we will publish releases via GitHub releases.

**Comment by sungam3r** [comment]
I mean it's **YOU** who decides to use one or another version/tag in https://github.com/ArieGato/serilog-sinks-rabbitmq/releases/new . GitHub Actions infrastructure places your tag on commit that triggers `publish release` workflow. MinVer then will just use tag from that commit as is. Of cource for all next commits from dev branches MinVer will increment version accordingly trimming leading `v`.

**Comment by sungam3r** [comment]
> So it supports v tags out of the box when we publish a release via github?

No. OK. Let's go on with `MinVerTagPrefix` = `v` and will see how it works. I'm fine either way.

**Pull request closed without merging**
